// ==UserScript==
// @name         DesuDesuTalk
// @namespace    udp://desushelter/*
// @version      0.4.87
// @description  Write something useful!
// @include      *://dobrochan.com/*/*
// @include      *://dobrochan.ru/*/*
// @include      *://dobrochan.org/*/*
// @include      *://inach.org/*/*
// @include      *://8chan.co/*/*
// @include      *://hatechan.co/*/*
// @include      *://8ch.net/*/*
// @include      *://www.8ch.net/*/*
// @include      *://oxwugzccvk3dk6tj.onion/*/*
// @include      *://lainchan.org/*/*
// @include      *://iichan.hk/*/*
// @include      *://2-ch.su/*/*
// @include      *://syn-ch.com/*/*
// @include      *://syn-ch.org/*/*
// @include      *://syn-ch.ru/*/*
// @include      *://krautchan.net/*/*
// @include      *://boards.4chan.org/*/*
// @include      *://boards.4channel.org/*/*
// @include      *://2ch.hk/*/*
// @include      *://2ch.re/*/*
// @include      *://2ch.pm/*/*
// @include      *://2ch.tf/*/*
// @include      *://2ch.wf/*/*
// @include      *://2ch.yt/*/*
// @include      *://2-ch.so/*/*
// @include      *://dva-ch.net/*/*
// @include      *://02ch.su/*/*
// @include      *://dmirrgetyojz735v.onion/*/*
// @include      *://2-chru.net/*/*
// @include      *://mirror.2-chru.net/*/*
// @include      *://bypass.2-chru.net/*/*
// @include      *://2chru.cafe/*/*
// @include      *://2-chru.cafe/*/*
// @include      *://127.0.0.1:7345/*
// @include      *://ech.su/*
// @include      *://8ch.pl/*/*
// @include      *://8ch.vichandcxw4gm3wy.onion/*/*
// @exclude      *#dev
// @copyright    2014+, Boku
// @icon         https://github.com/desudesutalk/desudesutalk/raw/master/icon.jpg
// @updateURL    https://github.com/desudesutalk/desudesutalk/raw/master/ddt.meta.js
// @run-at       document-start
// @grant        GM_xmlhttpRequest
// @grant        GM_getValue
// @grant        GM_setValue
// @grant        GM_deleteValue
// @grant        unsafeWindow
// ==/UserScript==
